apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2026-06-28T14:16:58Z"
  labels:
    app: frontend
  name: frontend
  namespace: default
  resourceVersion: "40170"
  uid: 8b4102e7-5c9e-4c59-9fe1-b83e3f47cab7
spec:
  clusterIP: 10.43.222.45
  clusterIPs:
  - 10.43.222.45
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 8082
    protocol: TCP
    targetPort: 8082
  selector:
    app: frontend
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
